### ISSUE TITLE
seeking help getting zabbix agent working on armHF, might be able to assist back with docs & tests etc.

### ISSUE THREAD

**Issue by xenek** [pschmitt/docker-armhf-zabbix-agent#1]
(This is a copy/paste duplicate of a issue comment you raised on the official zabbix docker agent GitHub repo, posted here because it's also appropriate. )

Note, I don't mind helping by sharing instructions & setup / config notes, and then maybe someone with a Pi 3b (not the 64 bit Pi 3b+) can contribute further ontop of the odroid setup notes.

Hi pschmitt, 

I'd also like an official Arm build that allows use of eg. Docker via Portainer on Rasberry Pi to be monitored via Zabbix Agent.

So, just trying this now, on my Odroid XU4 (also armhf or arm32v7) much like a Raspberry Pi,
Base OS is Ubuntu Mate 16.04.04 LTS  I think.

I see https://hub.docker.com/r/pschmitt/zabbix-agent-alpine-armhf/ is pretty empty, is there a plan for instructions? I'm using Portainer on Arm, not the terminal ;-)

Also see you have some stuff here.
https://github.com/pschmitt?utf8=%E2%9C%93&tab=repositories&q=zabbix&type=&language=

Here are my portainer Docker Gui setup 'notes'

Zabbix Agent (Arm HF / arm32v7 support!)
https://hub.docker.com/r/pschmitt/zabbix-agent-alpine-armhf/
Image Name pschmitt/zabbix-agent-alpine-armhf
Container name armzabbixagent
Always pull image
Don't publish exposed ports
No port mapping
Turn off access control
Set console to interactive & TTY
Set network to host, hostname to zabbixagent
Set restart policy
Set Runtime & Resources to Privileged 
Set both volumes with bind  /:/rootfs and /var/run:/var/run
(note host is the / and container is the /rootfs)
Set environment variables
 ZA_Server=yourprivatezabbixserver
 ZA_ServerActive=yourprivatezabbixserver

I tried this https://hub.docker.com/r/monitoringartist/dockbix-agent-xxl-limited/
but it responds with 
_init_linux.go:178: exec user process caused "exec format error"
Which is to be expected.

Yours looks much more promising, if I get all variables etc. right

(I've used monitoring artist's excellent instructions as a guide). The below is what I have so far. Any tips you can add those instructions would be great.

29T00:46:55.536110143Z ** Deploying Zabbix agent
,
29T00:46:55.536572057Z ** Preparing the system
,
29T00:46:55.537152178Z ** Preparing Zabbix agent
,
29T00:46:55.537508926Z ** Preparing Zabbix agent configuration file
,
29T00:46:55.543015935Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "PidFile": ''... removed
,
29T00:46:55.557517056Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "LogType": 'console'... added
,
29T00:46:55.561972488Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "LogFile": ''... removed
,
29T00:46:55.566427295Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "LogFileSize": ''... removed
,
29T00:46:55.570894060Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "DebugLevel": ''... removed
,
29T00:46:55.575279408Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "SourceIP": ''... removed
,
29T00:46:55.579933297Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "EnableRemoteCommands": ''... removed
,
29T00:46:55.585233891Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "LogRemoteCommands": ''... removed
,
29T00:46:55.585302390Z ** Using 'zabbix-server' servers for passive checks
,
29T00:46:55.597300568Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "Server": 'zabbix-server'... updated
,
29T00:46:55.601806042Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "ListenPort": ''... removed
,
29T00:46:55.606305806Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "ListenIP": ''... removed
,
29T00:46:55.610789988Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "StartAgents": ''... removed
,
29T00:46:55.610830363Z ** Using 'zabbix-server:10051' servers for active checks
,
29T00:46:55.622131628Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "ServerActive": 'zabbix-server:10051'... updated
,
29T00:46:55.626609518Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "Hostname": ''... removed
,
29T00:46:55.631073575Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "HostnameItem": ''... removed
,
29T00:46:55.635488757Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "HostMetadata": ''... removed
,
29T00:46:55.639991105Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "HostMetadataItem": ''... removed
,
29T00:46:55.644545703Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "RefreshActiveChecks": ''... removed
,
29T00:46:55.649175217Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "BufferSend": ''... removed
,
29T00:46:55.653712731Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "BufferSize": ''... removed
,
29T00:46:55.658213246Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "MaxLinesPerSecond": ''... removed
,
29T00:46:55.662462804Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "Timeout": ''... removed
,
29T00:46:55.676772218Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "Include": '/etc/zabbix/zabbix_agentd.d/'... added first occurrence
,
29T00:46:55.681593189Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "UnsafeUserParameters": ''... removed
,
29T00:46:55.695808896Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "LoadModulePath": '/var/lib/zabbix/modules/'... added
,
29T00:46:55.700934199Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSConnect": ''... removed
,
29T00:46:55.705428172Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSAccept": ''... removed
,
29T00:46:55.709815562Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSCAFile": ''... removed
,
29T00:46:55.714396743Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSCRLFile": ''... removed
,
29T00:46:55.719034549Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSServerCertIssuer": ''... removed
,
29T00:46:55.723578522Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSServerCertSubject": ''... removed
,
29T00:46:55.728109703Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSCertFile": ''... removed
,
29T00:46:55.732898299Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSKeyFile": ''... removed
,
29T00:46:55.737389939Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSPSKIdentity": ''... removed
,
29T00:46:55.741815996Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSPSKFile": ''... removed
,
29T00:46:55.742375326Z ** Cleaning the system
,
29T00:46:55.742403118Z ########################################################
,
29T00:46:55.742988031Z ** Starting Zabbix agent
,
29T00:46:55.752599640Z Starting Zabbix Agent [zabbixagent]. Zabbix 3.4.8 (revision 79252).
,
29T00:46:55.752721806Z Press Ctrl+C to exit.
,
29T00:46:55.752762514Z 
,
29T00:46:55.752796889Z      1:20180429:004655.752 Starting Zabbix Agent [zabbixagent]. Zabbix 3.4.8 (revision 79252).
,
29T00:46:55.752832138Z      1:20180429:004655.752 **** Enabled features ****
,
29T00:46:55.752866347Z      1:20180429:004655.752 IPv6 support:          YES
,
29T00:46:55.752917971Z      1:20180429:004655.752 TLS support:           YES
,
29T00:46:55.752953554Z      1:20180429:004655.752 **************************
,
29T00:46:55.752987763Z      1:20180429:004655.752 using configuration file: /etc/zabbix/zabbix_agentd.conf
,
29T00:46:55.753027137Z      1:20180429:004655.752 agent #0 started [main process]
,
29T00:46:55.754053048Z     55:20180429:004655.753 agent #1 started [collector]
,
29T00:46:55.759108268Z     56:20180429:004655.754 agent #2 started [listener #1]
,
29T00:46:55.759176184Z     57:20180429:004655.754 agent #3 started [listener #2]
,
29T00:46:55.759235517Z     58:20180429:004655.755 agent #4 started [listener #3]
,
29T00:46:55.759260558Z     59:20180429:004655.755 agent #5 started [active checks #1]
,
29T00:46:55.768560711Z     59:20180429:004655.768 active check configuration update from [zabbix-server:10051] started to fail (cannot resolve [zabbix-server])
,

**Comment by pschmitt** [comment]
> No port mapping

~~You probably want to publish port 10050.~~
~~See the example here: https://github.com/pschmitt/docker-armhf-zabbix-agent/blob/master/run.sh~~

**EDIT**: Nevermind, I didn't read your issue correctly. 
If you want to monitor Docker containers you'll have to bind-mount the Docker socket (`/var/run/docker.sock`) and will probably need to cross-compile [zabbix_module_docker](https://github.com/monitoringartist/zabbix-docker-monitoring/blob/master/src/modules/zabbix_module_docker/zabbix_module_docker.c)
In any case this is out of the scope of this here repository. Closing.
